[mypy]
python_version = 3.12
warn_return_any = False
warn_unused_configs = True
ignore_missing_imports = True
no_implicit_optional = True
check_untyped_defs = False
disallow_untyped_defs = False
exclude = (?x)(
          backend/tests/
          | backend/data/
          | frontend/
          )

[mypy-tests.*]
ignore_errors = True
